# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18U8sfPEm5nXjK97pK7nU7vjcuISlJqrw
"""



"""# Experimento de Chunking — 10 Estratégias

## Documentos utilizados

- bioetica_e_ia.md
- escrita_academica_ia.md
- twitter_algoritmo.md

## Objetivo

Comparar 10 estratégias de divisão de documentos (chunking),
gerar embeddings dos chunks e realizar busca semântica
utilizando similaridade de cosseno e TOP 3 resultados.

## Perguntas

1. O que é Autonomia e opacidade algorítmica?
2. O que é o diário de bordo da IA?
3. Qual o impacto dos algoritmos nas redes sociais e no espaço público?
"""

!pip install -q langchain-text-splitters sentence-transformers scikit-learn nltk pandas

import os
import re
import json
import pandas as pd
import numpy as np

from pathlib import Path

from langchain_text_splitters import (
    CharacterTextSplitter,
    RecursiveCharacterTextSplitter,
    MarkdownHeaderTextSplitter
)

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

print("✅ Bibliotecas importadas com sucesso!")

import nltk

nltk.download("punkt")
nltk.download("punkt_tab")

print("✅ NLTK preparado!")

from google.colab import files

arquivos_enviados = files.upload()

print("\n📚 Arquivos enviados:")
for nome in arquivos_enviados.keys():
    print("✅", nome)

arquivos_md = [
    "bioetica_e_ia.md",
    "escrita_academica_ia.md",
    "twitter_algoritmo.md"
]

print("📚 DOCUMENTOS DA ATIVIDADE")
print("=" * 60)

for arquivo in arquivos_md:
    if os.path.exists(arquivo):
        tamanho = os.path.getsize(arquivo)
        print(f"✅ {arquivo} — encontrado")
    else:
        print(f"❌ {arquivo} — NÃO ENCONTRADO")

documentos = {}

for arquivo in arquivos_md:
    with open(arquivo, "r", encoding="utf-8") as f:
        documentos[arquivo] = f.read()

print("📚 DOCUMENTOS CARREGADOS")
print("=" * 60)

for arquivo, texto in documentos.items():
    print(f"✅ {arquivo}: {len(texto)} caracteres")

# ============================================================
# 10 ESTRATÉGIAS DE CHUNKING
# ============================================================

# ------------------------------------------------------------
# TESTES 1 A 6 — CHUNKING FIXO
# ------------------------------------------------------------

def chunk_fixo(texto, tamanho, overlap):
    splitter = CharacterTextSplitter(
        separator="",
        chunk_size=tamanho,
        chunk_overlap=overlap,
        length_function=len,
        keep_separator=False
    )

    return splitter.split_text(texto)


def grupo_1(texto):
    return chunk_fixo(texto, 200, 0)


def grupo_2(texto):
    return chunk_fixo(texto, 500, 0)


def grupo_3(texto):
    return chunk_fixo(texto, 1000, 0)


def grupo_4(texto):
    return chunk_fixo(texto, 2000, 0)


def grupo_5(texto):
    return chunk_fixo(texto, 500, 50)


def grupo_6(texto):
    return chunk_fixo(texto, 500, 200)


# ------------------------------------------------------------
# TESTE 7 — POR PARÁGRAFO
# ------------------------------------------------------------

def grupo_7(texto):
    texto = texto.replace("\r\n", "\n")

    paragrafos = re.split(r"\n\s*\n+", texto.strip())

    return [
        paragrafo.strip()
        for paragrafo in paragrafos
        if paragrafo.strip()
    ]


# ------------------------------------------------------------
# TESTE 8 — POR SENTENÇA, AGRUPANDO 3
# ------------------------------------------------------------

def grupo_8(texto):
    texto = texto.replace("\r\n", "\n").strip()

    sentencas = re.split(
        r"(?<=[.!?])\s+",
        texto
    )

    sentencas = [
        sentenca.strip()
        for sentenca in sentencas
        if sentenca.strip()
    ]

    chunks = []

    for i in range(0, len(sentencas), 3):
        grupo = sentencas[i:i + 3]

        chunks.append(
            " ".join(grupo)
        )

    return chunks


# ------------------------------------------------------------
# TESTE 9 — RECURSIVO / SEPARADORES HIERÁRQUICOS
# ------------------------------------------------------------

def grupo_9(texto):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=0,
        length_function=len,
        separators=[
            "\n\n",
            "\n",
            " ",
            ""
        ]
    )

    return splitter.split_text(texto)


# ------------------------------------------------------------
# TESTE 10 — SEÇÕES / HEADINGS MARKDOWN
# ------------------------------------------------------------

def grupo_10(texto):

    # Alguns headings dos arquivos estão escritos como:
    # \## Título
    #
    # O splitter Markdown espera:
    # ## Título
    #
    # Então corrigimos SOMENTE a marcação do heading
    # para que o splitter consiga reconhecê-la.

    texto_normalizado = re.sub(
        r"^(\\)(#{1,6})(\s+)",
        r"\2\3",
        texto,
        flags=re.MULTILINE
    )

    headers_to_split_on = [
        ("#", "Título"),
        ("##", "Seção"),
        ("###", "Subseção"),
        ("####", "Subsubseção")
    ]

    splitter = MarkdownHeaderTextSplitter(
        headers_to_split_on=headers_to_split_on,
        strip_headers=False
    )

    documentos = splitter.split_text(texto_normalizado)

    return [
        documento.page_content.strip()
        for documento in documentos
        if documento.page_content.strip()
    ]


# ------------------------------------------------------------
# ORGANIZAÇÃO DOS 10 GRUPOS
# ------------------------------------------------------------

estrategias = {
    1: grupo_1,
    2: grupo_2,
    3: grupo_3,
    4: grupo_4,
    5: grupo_5,
    6: grupo_6,
    7: grupo_7,
    8: grupo_8,
    9: grupo_9,
    10: grupo_10
}


nomes_estrategias = {
    1: "Fixo - 200 caracteres - overlap 0",
    2: "Fixo - 500 caracteres - overlap 0",
    3: "Fixo - 1000 caracteres - overlap 0",
    4: "Fixo - 2000 caracteres - overlap 0",
    5: "Fixo - 500 caracteres - overlap 50",
    6: "Fixo - 500 caracteres - overlap 200",
    7: "Por parágrafo",
    8: "Por sentença - agrupando 3",
    9: "Recursivo - separadores hierárquicos",
    10: "Por seção - Markdown Headers"
}

print("✅ As 10 estratégias foram definidas!")

print("🔎 CONFERÊNCIA DAS ESTRATÉGIAS")
print("=" * 70)

for numero, nome in nomes_estrategias.items():
    print(f"Teste {numero}: {nome}")

# ============================================================
# EXECUÇÃO DOS 10 TESTES NOS 3 DOCUMENTOS
# ============================================================

todos_os_chunks = {}

for numero_grupo, estrategia in estrategias.items():

    nome_teste = nomes_estrategias[numero_grupo]

    todos_os_chunks[nome_teste] = {}

    print("\n")
    print("=" * 80)
    print(f"TESTE {numero_grupo} — {nome_teste}")
    print("=" * 80)

    for nome_arquivo in arquivos_md:

        texto = documentos[nome_arquivo]

        chunks = estrategia(texto)

        todos_os_chunks[nome_teste][nome_arquivo] = chunks

        print(
            f"📄 {nome_arquivo}: "
            f"{len(chunks)} chunks"
        )

print("\n")
print("=" * 80)
print("✅ OS 10 TESTES FORAM EXECUTADOS NOS 3 DOCUMENTOS!")
print("=" * 80)

avaliacoes = []

for nome_teste, documentos_teste in todos_os_chunks.items():

    for arquivo, chunks in documentos_teste.items():

        tamanhos = [
            len(chunk)
            for chunk in chunks
        ]

        avaliacoes.append({
            "Arquivo": arquivo,
            "Teste": nome_teste,
            "Total de chunks": len(chunks),
            "Tamanho médio": round(
                sum(tamanhos) / len(tamanhos), 2
            ) if tamanhos else 0,
            "Menor chunk": min(tamanhos) if tamanhos else 0,
            "Maior chunk": max(tamanhos) if tamanhos else 0
        })

df_resumo = pd.DataFrame(avaliacoes)

display(df_resumo)

print("Quantidade de linhas:", len(df_resumo))

print("\nQuantidade esperada:")
print("10 testes × 3 documentos = 30 linhas")

print("\nQuantidade real:", len(df_resumo))

print("\nTestes encontrados:")
print(
    sorted(
        df_resumo["Teste"].unique()
    )
)

modelo_embeddings = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

print("✅ Modelo de embeddings carregado!")
print(
    "Dimensão dos embeddings:",
    modelo_embeddings.get_sentence_embedding_dimension()
)

texto_teste = (
    "A inteligência artificial pode auxiliar na medicina."
)

embedding_teste = modelo_embeddings.encode(
    texto_teste
)

print("Texto:")
print(texto_teste)

print("\nTipo do resultado:")
print(type(embedding_teste))

print("\nDimensão:")
print(embedding_teste.shape)

print("\nPrimeiros 5 valores:")
print(embedding_teste[:5])

modelo_embeddings = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

print("✅ Modelo de embeddings carregado!")
print(
    "Dimensão dos embeddings:",
    modelo_embeddings.get_sentence_embedding_dimension()
)

texto_teste = (
    "A inteligência artificial pode auxiliar na medicina."
)

embedding_teste = modelo_embeddings.encode(
    texto_teste
)

print("Texto:")
print(texto_teste)

print("\nTipo do resultado:")
print(type(embedding_teste))

print("\nDimensão:")
print(embedding_teste.shape)

print("\nPrimeiros 5 valores:")
print(embedding_teste[:5])

print("Variáveis relacionadas aos chunks:")
print()

for nome in dir():
    if "chunk" in nome.lower() or "resultado" in nome.lower():
        print(nome)

print("Variáveis relacionadas aos chunks:")
print()

for nome in dir():
    if "chunk" in nome.lower() or "resultado" in nome.lower():
        print(nome)

print("Tipo de todos_os_chunks:")
print(type(todos_os_chunks))

print("\nQuantidade de elementos:")
print(len(todos_os_chunks))

len(todos_os_chunks)

print("Quantidade de elementos:", len(todos_os_chunks))
print()

for i, item in enumerate(todos_os_chunks):
    print("Elemento", i)
    print("Tipo:", type(item))

    if hasattr(item, "keys"):
        print("Chaves:", list(item.keys()))
    elif isinstance(item, list):
        print("Quantidade dentro:", len(item))

    print("-" * 60)

print("Tipo de todos_os_chunks:")
print(type(todos_os_chunks))

print("\nQuantidade de elementos:")
print(len(todos_os_chunks))

print("\nChaves de todos_os_chunks:")
print(list(todos_os_chunks.keys()))

estrategia_teste = "Fixo - 200 caracteres - overlap 0"

print("Estratégia escolhida:")
print(estrategia_teste)

print("\nTipo do conteúdo:")
print(type(todos_os_chunks[estrategia_teste]))

print("\nQuantidade de elementos:")
print(len(todos_os_chunks[estrategia_teste]))

estrategia_teste = "Fixo - 200 caracteres - overlap 0"

print("Estratégia escolhida:")
print(estrategia_teste)

print("\nTipo do conteúdo:")
print(type(todos_os_chunks[estrategia_teste]))

print("\nQuantidade de elementos:")
print(len(todos_os_chunks[estrategia_teste]))

print("Documentos dentro da estratégia:")
print()

for documento in todos_os_chunks[estrategia_teste]:
    print("-", documento)

documento_teste = "bioetica_e_ia.md"

chunks_teste = todos_os_chunks[estrategia_teste][documento_teste]

print("Documento:")
print(documento_teste)

print("\nTipo dos chunks:")
print(type(chunks_teste))

print("\nQuantidade de chunks:")
print(len(chunks_teste))

documento_teste = "bioetica_e_ia.md"

chunks_teste = todos_os_chunks[estrategia_teste][documento_teste]

print("Documento:")
print(documento_teste)

print("\nTipo dos chunks:")
print(type(chunks_teste))

print("\nQuantidade de chunks:")
print(len(chunks_teste))



print("Tipo do primeiro chunk:")
print(type(chunks_teste[0]))

print("\nTamanho do primeiro chunk:")
print(len(chunks_teste[0]))

print("\nConteúdo do primeiro chunk:")
print(chunks_teste[0])

embeddings_teste = modelo_embeddings.encode(
    chunks_teste,
    show_progress_bar=True
)

print("Embeddings gerados!")
print("Quantidade de embeddings:", len(embeddings_teste))
print("Dimensão dos embeddings:", embeddings_teste.shape)

embeddings_teste = modelo_embeddings.encode(
    chunks_teste,
    show_progress_bar=True
)

print("Embeddings gerados!")
print("Quantidade de embeddings:", len(embeddings_teste))
print("Dimensão dos embeddings:", embeddings_teste.shape)

registros_embeddings_teste = []

for i, (chunk, embedding) in enumerate(zip(chunks_teste, embeddings_teste)):
    registros_embeddings_teste.append({
        "estrategia": estrategia_teste,
        "documento": documento_teste,
        "chunk_id": i,
        "chunk": chunk,
        "embedding": embedding
    })

print("Registros criados:", len(registros_embeddings_teste))
print("\nPrimeiro registro:")
print("Estratégia:", registros_embeddings_teste[0]["estrategia"])
print("Documento:", registros_embeddings_teste[0]["documento"])
print("Chunk ID:", registros_embeddings_teste[0]["chunk_id"])
print("Tamanho do chunk:", len(registros_embeddings_teste[0]["chunk"]))
print("Dimensão do embedding:", len(registros_embeddings_teste[0]["embedding"]))

print("Quantidade de estratégias:", len(todos_os_chunks))
print("\nEstratégias encontradas:")

for i, estrategia in enumerate(todos_os_chunks.keys(), start=1):
    print(f"{i}. {estrategia}")

documentos_esperados = [
    "bioetica_e_ia.md",
    "escrita_academica_ia.md",
    "twitter_algoritmo.md"
]

print("Verificação dos documentos:\n")

for estrategia, documentos in todos_os_chunks.items():
    print(f"\n{estrategia}")

    for documento in documentos_esperados:
        if documento in documentos:
            print(f"  ✓ {documento}: {len(documentos[documento])} chunks")
        else:
            print(f"  ✗ {documento}: NÃO ENCONTRADO")

import pandas as pd

resumo_chunks = []

for estrategia, documentos in todos_os_chunks.items():
    for documento, chunks in documentos.items():
        resumo_chunks.append({
            "estrategia": estrategia,
            "documento": documento,
            "quantidade_chunks": len(chunks)
        })

df_resumo_chunks = pd.DataFrame(resumo_chunks)

print("Total de combinações:", len(df_resumo_chunks))
display(df_resumo_chunks)

df_resumo_chunks.to_csv(
    "resumo_chunks.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo resumo_chunks.csv criado com sucesso!")

todos_os_embeddings = {}

print("Iniciando geração dos embeddings...\n")

for estrategia, documentos in todos_os_chunks.items():

    todos_os_embeddings[estrategia] = {}

    print(f"\nEstratégia: {estrategia}")

    for documento, chunks in documentos.items():

        print(f"  Processando: {documento}")
        print(f"  Quantidade de chunks: {len(chunks)}")

        embeddings = modelo_embeddings.encode(
            chunks,
            show_progress_bar=False
        )

        todos_os_embeddings[estrategia][documento] = embeddings

        print(f"  Embeddings gerados: {len(embeddings)}")
        print(f"  Dimensão: {embeddings.shape}")

print("\nTodos os embeddings foram gerados!")

print("Estratégias com embeddings:", len(todos_os_embeddings))

total_experimentos = 0
total_embeddings = 0

for estrategia, documentos in todos_os_embeddings.items():

    for documento, embeddings in documentos.items():

        total_experimentos += 1
        total_embeddings += len(embeddings)

        print(
            f"{estrategia} | "
            f"{documento} | "
            f"{embeddings.shape}"
        )

print("\nTotal de experimentos:", total_experimentos)
print("Total de embeddings:", total_embeddings)

perguntas = [
    "O que é Autonomia e opacidade algorítmica?",
    "O que é o diário de bordo da IA?",
    "Qual o impacto dos algoritmos nas redes sociais e no espaço público?"
]

print("Quantidade de perguntas:", len(perguntas))

for i, pergunta in enumerate(perguntas, start=1):
    print(f"{i}. {pergunta}")

embeddings_perguntas = modelo_embeddings.encode(
    perguntas,
    show_progress_bar=True
)

print("Embeddings das perguntas gerados!")
print("Quantidade:", len(embeddings_perguntas))
print("Dimensão:", embeddings_perguntas.shape)

import numpy as np

def similaridade_cosseno(vetor_a, vetor_b):
    produto = np.dot(vetor_a, vetor_b)

    norma_a = np.linalg.norm(vetor_a)
    norma_b = np.linalg.norm(vetor_b)

    if norma_a == 0 or norma_b == 0:
        return 0.0

    return produto / (norma_a * norma_b)

pergunta_teste = perguntas[0]
embedding_pergunta_teste = embeddings_perguntas[0]

embeddings_documento_teste = todos_os_embeddings[
    estrategia_teste
][
    documento_teste
]

similaridades_teste = []

for i, embedding_chunk in enumerate(embeddings_documento_teste):

    similaridade = similaridade_cosseno(
        embedding_pergunta_teste,
        embedding_chunk
    )

    similaridades_teste.append({
        "chunk_id": i,
        "similaridade": similaridade,
        "chunk": chunks_teste[i]
    })

df_teste = pd.DataFrame(similaridades_teste)

df_teste = df_teste.sort_values(
    "similaridade",
    ascending=False
)

display(df_teste.head(3))

pergunta_teste = perguntas[0]
embedding_pergunta_teste = embeddings_perguntas[0]

embeddings_documento_teste = todos_os_embeddings[
    estrategia_teste
][
    documento_teste
]

similaridades_teste = []

for i, embedding_chunk in enumerate(embeddings_documento_teste):

    similaridade = similaridade_cosseno(
        embedding_pergunta_teste,
        embedding_chunk
    )

    similaridades_teste.append({
        "chunk_id": i,
        "similaridade": similaridade,
        "chunk": chunks_teste[i]
    })

df_teste = pd.DataFrame(similaridades_teste)

df_teste = df_teste.sort_values(
    "similaridade",
    ascending=False
)

display(df_teste.head(3))

df_teste_top3 = df_teste.head(3).copy()

df_teste_top3 = df_teste_top3.reset_index(drop=True)

df_teste_top3.insert(
    0,
    "posicao",
    range(1, len(df_teste_top3) + 1)
)

display(df_teste_top3)

print("Quantidade de estratégias:", len(todos_os_chunks))

print("\nEstratégias encontradas:")

for numero, estrategia in enumerate(todos_os_chunks.keys(), start=1):
    print(f"{numero}. {estrategia}")

print("Quantidade de estratégias:", len(todos_os_chunks))

print("\nEstratégias encontradas:")

for numero, estrategia in enumerate(todos_os_chunks.keys(), start=1):
    print(f"{numero}. {estrategia}")

documentos_esperados = [
    "bioetica_e_ia.md",
    "escrita_academica_ia.md",
    "twitter_algoritmo.md"
]

print("VERIFICAÇÃO DOS DOCUMENTOS")
print("=" * 70)

todos_corretos = True

for numero, (estrategia, documentos) in enumerate(
    todos_os_chunks.items(),
    start=1
):

    print(f"\n{numero}. {estrategia}")

    for documento in documentos_esperados:

        if documento in documentos:
            print(
                f"   ✓ {documento} "
                f"→ {len(documentos[documento])} chunks"
            )
        else:
            print(
                f"   ✗ {documento} → NÃO ENCONTRADO"
            )
            todos_corretos = False

print("\n" + "=" * 70)

if todos_corretos:
    print("✓ TODOS OS 30 EXPERIMENTOS POSSUEM OS 3 DOCUMENTOS.")
else:
    print("✗ EXISTE PELO MENOS UM DOCUMENTO AUSENTE.")

import pandas as pd

resumo_chunks = []

for estrategia, documentos in todos_os_chunks.items():

    for documento, chunks in documentos.items():

        resumo_chunks.append({
            "estrategia": estrategia,
            "documento": documento,
            "quantidade_chunks": len(chunks)
        })

df_resumo_chunks = pd.DataFrame(resumo_chunks)

print("Quantidade de experimentos:", len(df_resumo_chunks))

display(df_resumo_chunks)

import pandas as pd

resumo_chunks = []

for estrategia, documentos in todos_os_chunks.items():

    for documento, chunks in documentos.items():

        resumo_chunks.append({
            "estrategia": estrategia,
            "documento": documento,
            "quantidade_chunks": len(chunks)
        })

df_resumo_chunks = pd.DataFrame(resumo_chunks)

print("Quantidade de experimentos:", len(df_resumo_chunks))

display(df_resumo_chunks)

todos_os_embeddings = {}

print("=" * 70)
print("GERAÇÃO DOS EMBEDDINGS")
print("=" * 70)

for estrategia, documentos in todos_os_chunks.items():

    print(f"\nESTRATÉGIA: {estrategia}")

    todos_os_embeddings[estrategia] = {}

    for documento, chunks in documentos.items():

        print(
            f"  Documento: {documento}"
        )

        print(
            f"  Quantidade de chunks: {len(chunks)}"
        )

        embeddings = modelo_embeddings.encode(
            chunks,
            show_progress_bar=True
        )

        todos_os_embeddings[estrategia][documento] = embeddings

        print(
            f"  ✓ Embeddings: {len(embeddings)}"
        )

        print(
            f"  ✓ Dimensão: {embeddings.shape}"
        )

print("\n" + "=" * 70)
print("✓ TODOS OS EMBEDDINGS FORAM GERADOS!")

perguntas = [
    "O que é Autonomia e opacidade algorítmica?",
    "O que é o diário de bordo da IA?",
    "Qual o impacto dos algoritmos nas redes sociais e no espaço público?"
]

print("Quantidade de perguntas:", len(perguntas))

for numero, pergunta in enumerate(perguntas, start=1):
    print(f"{numero}. {pergunta}")

embeddings_perguntas = modelo_embeddings.encode(
    perguntas,
    show_progress_bar=True
)

print("Embeddings das perguntas gerados!")
print("Quantidade:", len(embeddings_perguntas))
print("Dimensão:", embeddings_perguntas.shape)

import numpy as np

def similaridade_cosseno(vetor_a, vetor_b):

    produto = np.dot(vetor_a, vetor_b)

    norma_a = np.linalg.norm(vetor_a)
    norma_b = np.linalg.norm(vetor_b)

    if norma_a == 0 or norma_b == 0:
        return 0.0

    return produto / (norma_a * norma_b)

import numpy as np

def similaridade_cosseno(vetor_a, vetor_b):

    produto = np.dot(vetor_a, vetor_b)

    norma_a = np.linalg.norm(vetor_a)
    norma_b = np.linalg.norm(vetor_b)

    if norma_a == 0 or norma_b == 0:
        return 0.0

    return produto / (norma_a * norma_b)



def buscar_top_3(
    pergunta_embedding,
    chunks,
    embeddings_chunks
):

    resultados = []

    for chunk_id, embedding_chunk in enumerate(
        embeddings_chunks
    ):

        similaridade = similaridade_cosseno(
            pergunta_embedding,
            embedding_chunk
        )

        resultados.append({
            "chunk_id": chunk_id,
            "similaridade": similaridade,
            "chunk": chunks[chunk_id]
        })

    resultados.sort(
        key=lambda x: x["similaridade"],
        reverse=True
    )

    return resultados[:3]

top_3_teste = buscar_top_3(
    embeddings_perguntas[0],
    chunks_teste,
    todos_os_embeddings[
        estrategia_teste
    ][
        documento_teste
    ]
)

for posicao, resultado in enumerate(
    top_3_teste,
    start=1
):

    print("=" * 70)
    print(f"TOP {posicao}")

    print(
        "Chunk ID:",
        resultado["chunk_id"]
    )

    print(
        "Similaridade:",
        f"{resultado['similaridade']:.6f}"
    )

    print("\nConteúdo:")
    print(resultado["chunk"])

todos_os_embeddings = {}

print("=" * 70)
print("GERAÇÃO DOS EMBEDDINGS")
print("=" * 70)

for estrategia, documentos in todos_os_chunks.items():

    print(f"\nESTRATÉGIA: {estrategia}")

    todos_os_embeddings[estrategia] = {}

    for documento, chunks in documentos.items():

        print(f"\n  Documento: {documento}")
        print(f"  Quantidade de chunks: {len(chunks)}")

        embeddings = modelo_embeddings.encode(
            chunks,
            show_progress_bar=True
        )

        todos_os_embeddings[estrategia][documento] = embeddings

        print(f"  ✓ Embeddings gerados: {len(embeddings)}")
        print(f"  ✓ Dimensão: {embeddings.shape}")

perguntas = [
    "O que é Autonomia e opacidade algorítmica?",
    "O que é o diário de bordo da IA?",
    "Qual o impacto dos algoritmos nas redes sociais e no espaço público?"
]

print("Quantidade de perguntas:", len(perguntas))

for numero, pergunta in enumerate(perguntas, start=1):
    print(f"{numero}. {pergunta}")

embeddings_perguntas = modelo_embeddings.encode(
    perguntas,
    show_progress_bar=True
)

print("\nEmbeddings das perguntas gerados!")
print("Quantidade:", len(embeddings_perguntas))
print("Dimensão:", embeddings_perguntas.shape)

def buscar_top_3(
    pergunta_embedding,
    chunks,
    embeddings_chunks
):

    resultados = []

    for chunk_id, embedding_chunk in enumerate(
        embeddings_chunks
    ):

        similaridade = similaridade_cosseno(
            pergunta_embedding,
            embedding_chunk
        )

        resultados.append({
            "chunk_id": chunk_id,
            "similaridade": similaridade,
            "chunk": chunks[chunk_id]
        })

    resultados.sort(
        key=lambda x: x["similaridade"],
        reverse=True
    )

    return resultados[:3]

top_3_teste = buscar_top_3(
    embeddings_perguntas[0],
    chunks_teste,
    todos_os_embeddings[
        estrategia_teste
    ][
        documento_teste
    ]
)

for posicao, resultado in enumerate(
    top_3_teste,
    start=1
):

    print("=" * 70)
    print(f"TOP {posicao}")

    print(
        "Chunk ID:",
        resultado["chunk_id"]
    )

    print(
        "Similaridade:",
        f"{resultado['similaridade']:.6f}"
    )

    print("\nConteúdo:")
    print(resultado["chunk"])

top_3_teste = buscar_top_3(
    embeddings_perguntas[0],
    chunks_teste,
    todos_os_embeddings[
        estrategia_teste
    ][
        documento_teste
    ]
)

for posicao, resultado in enumerate(
    top_3_teste,
    start=1
):

    print("=" * 70)
    print(f"TOP {posicao}")

    print(
        "Chunk ID:",
        resultado["chunk_id"]
    )

    print(
        "Similaridade:",
        f"{resultado['similaridade']:.6f}"
    )

    print("\nConteúdo:")
    print(resultado["chunk"])

print("=" * 70)
print("VERIFICAÇÃO DOS EMBEDDINGS")
print("=" * 70)

total_experimentos = 0
total_embeddings = 0
erros = 0

for estrategia, documentos in todos_os_embeddings.items():

    for documento, embeddings in documentos.items():

        total_experimentos += 1
        total_embeddings += len(embeddings)

        quantidade_chunks = len(
            todos_os_chunks[estrategia][documento]
        )

        dimensao = embeddings.shape[1]

        if len(embeddings) != quantidade_chunks:
            erros += 1

            print(
                f"✗ ERRO: {estrategia} | {documento}"
            )

        elif dimensao != 384:
            erros += 1

            print(
                f"✗ DIMENSÃO INCORRETA: "
                f"{estrategia} | {documento} | "
                f"{dimensao}"
            )

        else:
            print(
                f"✓ {estrategia} | "
                f"{documento} | "
                f"chunks={quantidade_chunks} | "
                f"embedding={embeddings.shape}"
            )

print("\n" + "=" * 70)
print("RESULTADO DA VERIFICAÇÃO")
print("=" * 70)

print("Total de experimentos:", total_experimentos)
print("Total de embeddings:", total_embeddings)
print("Erros:", erros)

print("=" * 70)
print("VERIFICAÇÃO DOS EMBEDDINGS")
print("=" * 70)

total_experimentos = 0
total_embeddings = 0
erros = 0

for estrategia, documentos in todos_os_embeddings.items():

    for documento, embeddings in documentos.items():

        total_experimentos += 1
        total_embeddings += len(embeddings)

        quantidade_chunks = len(
            todos_os_chunks[estrategia][documento]
        )

        dimensao = embeddings.shape[1]

        if len(embeddings) != quantidade_chunks:
            erros += 1

            print(
                f"✗ ERRO: {estrategia} | {documento}"
            )

        elif dimensao != 384:
            erros += 1

            print(
                f"✗ DIMENSÃO INCORRETA: "
                f"{estrategia} | {documento} | "
                f"{dimensao}"
            )

        else:
            print(
                f"✓ {estrategia} | "
                f"{documento} | "
                f"chunks={quantidade_chunks} | "
                f"embedding={embeddings.shape}"
            )

print("\n" + "=" * 70)
print("RESULTADO DA VERIFICAÇÃO")
print("=" * 70)

print("Total de experimentos:", total_experimentos)
print("Total de embeddings:", total_embeddings)
print("Erros:", erros)

embeddings_perguntas = modelo_embeddings.encode(
    perguntas,
    show_progress_bar=True
)

print("\nEmbeddings das perguntas gerados!")
print("Quantidade:", len(embeddings_perguntas))
print("Dimensão:", embeddings_perguntas.shape)

resultados_busca = []

print("=" * 70)
print("INICIANDO TODAS AS BUSCAS SEMÂNTICAS")
print("=" * 70)

for pergunta_id, pergunta in enumerate(
    perguntas,
    start=1
):

    print(
        f"\nPergunta {pergunta_id}/3:"
    )

    print(pergunta)

    pergunta_embedding = embeddings_perguntas[
        pergunta_id - 1
    ]

    for estrategia, documentos in todos_os_chunks.items():

        for documento, chunks in documentos.items():

            embeddings_chunks = todos_os_embeddings[
                estrategia
            ][documento]

            top_3 = buscar_top_3(
                pergunta_embedding,
                chunks,
                embeddings_chunks
            )

            for posicao, resultado in enumerate(
                top_3,
                start=1
            ):

                resultados_busca.append({

                    "pergunta_id": pergunta_id,

                    "pergunta": pergunta,

                    "estrategia": estrategia,

                    "documento": documento,

                    "posicao": posicao,

                    "chunk_id": resultado["chunk_id"],

                    "similaridade": resultado["similaridade"],

                    "chunk": resultado["chunk"]
                })

print("\n" + "=" * 70)
print("BUSCA SEMÂNTICA CONCLUÍDA")
print("=" * 70)

print(
    "Total de resultados:",
    len(resultados_busca)
)

df_resultados = pd.DataFrame(
    resultados_busca
)

print("Linhas:", len(df_resultados))
print("Colunas:", len(df_resultados.columns))

display(df_resultados.head(10))

df_resultados = pd.DataFrame(
    resultados_busca
)

print("Linhas:", len(df_resultados))
print("Colunas:", len(df_resultados.columns))

display(df_resultados.head(10))

verificacao_buscas = (
    df_resultados
    .groupby(
        [
            "pergunta_id",
            "estrategia",
            "documento"
        ]
    )
    .size()
    .reset_index(
        name="quantidade"
    )
)

print(
    "Quantidade de buscas:",
    len(verificacao_buscas)
)

print("\nResultados por busca:")

print(
    verificacao_buscas[
        "quantidade"
    ].value_counts()
)

erros_ordenacao = 0

for _, grupo in df_resultados.groupby(
    [
        "pergunta_id",
        "estrategia",
        "documento"
    ]
):

    grupo = grupo.sort_values(
        "posicao"
    )

    valores = grupo[
        "similaridade"
    ].tolist()

    if not (
        valores[0] >=
        valores[1] >=
        valores[2]
    ):

        erros_ordenacao += 1

print(
    "Erros de ordenação:",
    erros_ordenacao
)

df_resultados.to_csv(
    "resultados_busca_semantica.csv",
    index=False,
    encoding="utf-8-sig"
)

print(
    "✓ resultados_busca_semantica.csv criado com sucesso!"
)

resumo_busca = (
    df_resultados
    .groupby(
        [
            "pergunta_id",
            "estrategia",
            "documento"
        ]
    )
    .agg(
        melhor_similaridade=(
            "similaridade",
            "max"
        ),

        menor_similaridade_top3=(
            "similaridade",
            "min"
        ),

        media_top3=(
            "similaridade",
            "mean"
        )
    )
    .reset_index()
)

print(
    "Quantidade de buscas:",
    len(resumo_busca)
)

display(
    resumo_busca.head(10)
)

resumo_busca.to_csv(
    "resumo_busca_semantica.csv",
    index=False,
    encoding="utf-8-sig"
)

print(
    "✓ resumo_busca_semantica.csv criado!"
)

comparacao_estrategias = (
    df_resultados
    .groupby("estrategia")
    .agg(
        media_similaridade=(
            "similaridade",
            "mean"
        ),

        maior_similaridade=(
            "similaridade",
            "max"
        ),

        menor_similaridade=(
            "similaridade",
            "min"
        ),

        quantidade_resultados=(
            "similaridade",
            "count"
        )
    )
    .reset_index()
    .sort_values(
        "media_similaridade",
        ascending=False
    )
)

display(
    comparacao_estrategias
)

print(
    df_resultados
    .groupby("estrategia")
    .size()
)

print("=" * 70)
print("VALIDAÇÃO FINAL DOS RESULTADOS")
print("=" * 70)

print(
    "Total de resultados:",
    len(df_resultados)
)

print(
    "Quantidade de buscas:",
    len(verificacao_buscas)
)

print("\nResultados por posição:")

print(
    df_resultados["posicao"]
    .value_counts()
    .sort_index()
)

print("\nErros de ordenação:")
print(erros_ordenacao)

df_resultados.to_csv(
    "resultados_busca_semantica.csv",
    index=False,
    encoding="utf-8-sig"
)

print(
    "✓ resultados_busca_semantica.csv criado com sucesso!"
)

resumo_busca = (
    df_resultados
    .groupby(
        [
            "pergunta_id",
            "estrategia",
            "documento"
        ]
    )
    .agg(
        melhor_similaridade=(
            "similaridade",
            "max"
        ),
        menor_similaridade_top3=(
            "similaridade",
            "min"
        ),
        media_top3=(
            "similaridade",
            "mean"
        )
    )
    .reset_index()
)

display(resumo_busca)

resumo_busca.to_csv(
    "resumo_busca_semantica.csv",
    index=False,
    encoding="utf-8-sig"
)

print(
    "✓ resumo_busca_semantica.csv criado!"
)

comparacao_estrategias = (
    df_resultados
    .groupby("estrategia")
    .agg(
        media_similaridade=("similaridade", "mean"),
        maior_similaridade=("similaridade", "max"),
        menor_similaridade=("similaridade", "min"),
        quantidade_resultados=("similaridade", "count")
    )
    .reset_index()
    .sort_values(
        "media_similaridade",
        ascending=False
    )
)

display(comparacao_estrategias)

comparacao_por_pergunta = (
    df_resultados
    .groupby(
        [
            "pergunta_id",
            "pergunta",
            "estrategia"
        ]
    )
    .agg(
        media_similaridade=("similaridade", "mean"),
        melhor_similaridade=("similaridade", "max")
    )
    .reset_index()
)

display(
    comparacao_por_pergunta
)

top_1 = (
    df_resultados[
        df_resultados["posicao"] == 1
    ]
    .sort_values(
        "similaridade",
        ascending=False
    )
)

display(
    top_1[
        [
            "pergunta_id",
            "pergunta",
            "estrategia",
            "documento",
            "chunk_id",
            "similaridade",
            "chunk"
        ]
    ]
)

pergunta_1 = df_resultados[
    df_resultados["pergunta_id"] == 1
].sort_values(
    [
        "estrategia",
        "documento",
        "posicao"
    ]
)

display(pergunta_1)

pergunta_2 = df_resultados[
    df_resultados["pergunta_id"] == 2
].sort_values(
    [
        "estrategia",
        "documento",
        "posicao"
    ]
)

display(pergunta_2)

pergunta_3 = df_resultados[
    df_resultados["pergunta_id"] == 3
].sort_values(
    [
        "estrategia",
        "documento",
        "posicao"
    ]
)

display(pergunta_3)

comparacao_estrategias = (
    df_resultados
    .groupby("estrategia")
    .agg(
        media_similaridade=("similaridade", "mean"),
        maior_similaridade=("similaridade", "max"),
        menor_similaridade=("similaridade", "min"),
        quantidade_resultados=("similaridade", "count")
    )
    .reset_index()
    .sort_values(
        "media_similaridade",
        ascending=False
    )
)

display(comparacao_estrategias)

pergunta_1 = df_resultados[
    df_resultados["pergunta_id"] == 1
].sort_values(
    [
        "estrategia",
        "documento",
        "posicao"
    ]
)

display(
    pergunta_1[
        [
            "estrategia",
            "documento",
            "posicao",
            "chunk_id",
            "similaridade",
            "chunk"
        ]
    ]
)

top1_pergunta1 = df_resultados[
    (df_resultados["pergunta_id"] == 1) &
    (df_resultados["posicao"] == 1)
].sort_values(
    "similaridade",
    ascending=False
)

display(
    top1_pergunta1[
        [
            "estrategia",
            "documento",
            "chunk_id",
            "similaridade",
            "chunk"
        ]
    ]
)

top1_pergunta2 = df_resultados[
    (df_resultados["pergunta_id"] == 2) &
    (df_resultados["posicao"] == 1)
].sort_values(
    "similaridade",
    ascending=False
)

display(
    top1_pergunta2[
        [
            "estrategia",
            "documento",
            "chunk_id",
            "similaridade",
            "chunk"
        ]
    ]
)

top1_pergunta3 = df_resultados[
    (df_resultados["pergunta_id"] == 3) &
    (df_resultados["posicao"] == 1)
].sort_values(
    "similaridade",
    ascending=False
)

display(
    top1_pergunta3[
        [
            "estrategia",
            "documento",
            "chunk_id",
            "similaridade",
            "chunk"
        ]
    ]
)

analise_top3 = (
    df_resultados
    .groupby(
        [
            "pergunta_id",
            "estrategia"
        ]
    )
    .agg(
        media_top3=("similaridade", "mean"),
        melhor_resultado=("similaridade", "max"),
        pior_resultado=("similaridade", "min")
    )
    .reset_index()
    .sort_values(
        [
            "pergunta_id",
            "media_top3"
        ],
        ascending=[True, False]
    )
)

display(analise_top3)

ranking_final = (
    analise_top3
    .groupby("estrategia")
    .agg(
        media_geral_top3=("media_top3", "mean"),
        melhor_pergunta=("media_top3", "max"),
        pior_pergunta=("media_top3", "min")
    )
    .reset_index()
    .sort_values(
        "media_geral_top3",
        ascending=False
    )
)

display(ranking_final)

ranking_final = (
    analise_top3
    .groupby("estrategia")
    .agg(
        media_geral_top3=("media_top3", "mean"),
        melhor_pergunta=("media_top3", "max"),
        pior_pergunta=("media_top3", "min")
    )
    .reset_index()
    .sort_values(
        "media_geral_top3",
        ascending=False
    )
)

display(ranking_final)

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

plt.barh(
    ranking_final["estrategia"],
    ranking_final["media_geral_top3"]
)

plt.xlabel("Média geral de similaridade (TOP 3)")
plt.ylabel("Estratégia")
plt.title("Comparação das estratégias de chunking")

plt.gca().invert_yaxis()

plt.tight_layout()
plt.show()

resumo_final = ranking_final.copy()

resumo_final["ranking"] = range(1, len(resumo_final) + 1)

resumo_final = resumo_final[
    [
        "ranking",
        "estrategia",
        "media_geral_top3",
        "melhor_pergunta",
        "pior_pergunta"
    ]
]

display(resumo_final)

resumo_final.to_csv(
    "ranking_final_estrategias.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✓ ranking_final_estrategias.csv criado!")